using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace ThreadingSample.SourceGenerators
{
    [Generator]
    public class BackgroundTaskGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var provider = context.SyntaxProvider.ForAttributeWithMetadataName(
                fullyQualifiedMetadataName: "ThreadingSample.BackgroundTaskAttribute",
                predicate: IsCandidate,
                transform: static (ctx, _) =>
                {                
                    ISymbol classSymbol = ctx.TargetSymbol;

                    return new ClassModel(
                        classSymbol.Name,
                        classSymbol.ContainingNamespace.ToDisplayString()
                    );
                });
            
            context.RegisterSourceOutput(provider, Execute);
        }
        public static bool IsCandidate(SyntaxNode node, CancellationToken cancellationToken)
        {
            return node is ClassDeclarationSyntax clss && clss.Modifiers.Any(m => m.ValueText == "static") && clss.Modifiers.Any(m => m.ValueText == "partial");
        }

        private static void Execute(SourceProductionContext context, ClassModel model)
        {
            StringBuilder sb = new StringBuilder($$"""
                // <auto-generated/>
                using System;
                using System.Threading;
                using System.Runtime.CompilerServices;

                namespace {{model.Namespace}}
                {
                    public static partial class {{model.ClassName}}
                    {
                        [ModuleInitializer]
                        internal static void InitializeTask()
                        {
                            Thread backgroundThread = new Thread({{model.ClassName}}.DoWork);
                            backgroundThread.IsBackground = true;
                            backgroundThread.Start();
                        }
                    }
                }
                """);

            context.AddSource($"{model.ClassName}_BackgroundTask.g.cs", sb.ToString());

        }
        private record ClassModel(string ClassName, string Namespace);
    }

}
